import type { Metadata, Viewport } from "next"
import { OpenGraph } from "next/dist/lib/metadata/types/opengraph-types"
import { Geist, Geist_Mono, League_Spartan } from "next/font/google"
import { Suspense } from "react"
import "./globals.css"

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const openGraph: OpenGraph = {
  title: "Frontend Mentor | Calculator App Challenge",
  description:
    "This is a code solution to Frontend Mentor's calculator app challenge, generated by create next app",
  url: "https://fementor-calculator.netlify.app/",
  type: "website",
  siteName: "Frontend Mentor Calculator App",
  images: ["/public/favicon.png"],
}

export const metadata: Metadata = {
  metadataBase: new URL("https://fementor-calculator.netlify.app/"),
  title: {
    default: "Frontend Mentor | Calculator App Challenge",
    template: "%s | KC Ng",
  },
  description:
    "This is a code solution to Frontend Mentor's calculator app challenge, generated by create next app",
  authors: [{ name: "KC Ng", url: "https://kcng.netlify.app" }],
  keywords: ["frontend", "calculator app", "nextjs", "react"],
  openGraph: {
    ...openGraph,
    type: "website",
    locale: "en_US",
  },
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#ffffff",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={null}>{children}</Suspense>
      </body>
    </html>
  )
}
